language: android
sudo: false

android:
    components:
        - tools
        - build-tools-23.0.3

        # Additional components
        - extra-google-google_play_services
        - android-24
        - platform-tools
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-google-google_play_services    
        
        # Emulator for the tests
        - sys-img-armeabi-v7a-android-24    

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
    
branches:
  only:
    - develop

jdk: oraclejdk8

notifications:
  email: false
  

before_script:
    - chmod +x gradlew

script: ./gradlew clean build